on:
    release:
        types:
          - published

name: Push to game template

jobs:
    game-template:
        uses: deep-entertainment/egoventure-game-template/.github/workflows/game-template.yml@main
        with:
            addon: parrot
            branch: "main"
